name: Massage Olpe
favicon: null
layout_spectrum: 0.99451
typography_spectrum: 0.9465873145963997
title: Massage im Freizeitbad Olpe
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#8cb633'
    - '#706e6f'
    - '#b7b7b7'
    - '#979797'
  brandStrength: 0.002158996183425188
  lightness: 0.051774450577795506
  saturation: 0.4690707214176655
  rhythmicContrast: 0.35417213244363666
purpose: []
