name: Massage Olpe
favicon: null
layout_spectrum: 0.99451
typography_spectrum: 0.53361
title: Massage im Freizeitbad Olpe
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#8cb633'
    - '#706e6f'
    - '#b7b7b7'
    - '#979797'
  brandStrength: 1
  lightness: 0.5625
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
