name: massage-olpe
favicon: null
layout_spectrum: 0.6657768480945379
typography_spectrum: 0.9465873145963997
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.002158996183425188
  lightness: 0.051774450577795506
  saturation: 0.4690707214176655
  rhythmicContrast: 0.35417213244363666
purpose: []
